### PR TITLE
Keep at most max_colors in the resulting Palette

### PR DESCRIPTION
**Pull request by philn**

### CODE REVIEW

**Comment by philn** [comment]
CC @RazrFalcon @sdroege

**Comment by sdroege** [comment]
https://github.com/RazrFalcon/color-thief-rs/pull/4/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R88 should probably be `>= 1` or not?

**Comment by sdroege** [comment]
But makes sense to me otherwise, just not sure if the algorithm should've already ensured that there never more than `max_colors` returned (i.e. there might be another bug somewhere).

**Comment by philn** [comment]
Yes there is an assert about this earlier in the call site function

**Comment by philn** [comment]
For context, I observed that with `max_colors == 2`  I was getting a palette containing 3 items. I'm not sure indeed if this patch is the right solution, or merely a workaround for another bug.

**Comment by RazrFalcon** [comment]
Thanks!

**Pull request merged**
